### PR TITLE
Changed modifierFlags type to NSEventModifierFlags.

### PR DESCRIPTION
**Pull request by pointum**
Changed modifierFlags type to NSEventModifierFlags. Xcode 8.1 upgrade check without changes.

### CODE REVIEW

**Comment by pointum** [comment]
This is for Swift compatibility. Also keyCode probably should be NSInteger instead of NSUinteger, since kVK_ are imported as Int in Swift.

**Comment by pointum** [comment]
Ooh, I did not intend to bring in the the nullability checks in the pull request yet. Is that automatic from my upstream? 
The test fails because a shortcut is created with NULL action. Does it make sense to create a shortcut with no action?

**Comment by shpakovski** [comment]
Thanks a lot, I will review this when I have time. Sorry for the slow reply!

**Comment by pointum** [comment]
Thank you. See my previous comment for the test explanation. While annotating I presumed that action for a shortcut should not be NULL, but there's -[MASShortcutMonitor registerShortcut:shortcut withAction:NULL] line in the test.

**Comment by zoul** [comment]
Thank you very much for the changes and sorry for being so slow ☺️ I have ported the changes to current master, see #128. That should be fairly easy to review and merge.

**Pull request closed without merging**
