### PR TITLE
Swift Package Manager support + Big Sur UI fixes

### PR DESCRIPTION
**Pull request by sweetppro**
this fixes issues with other spm forks not compiling in Swift based projects.
no bridging header is required, just use:
`import MASShortcut`

or for SPM in ObjC:
`#import <Shortcut.h>`

### CODE REVIEW

**Comment by pointum** [comment]
Hi! The symbolic links in `include` folder point to absolute paths starting with `/Users/mrqwirk/`.

**Comment by sweetppro** [comment]
> Hi! The symbolic links in `include` folder point to absolute paths starting with `/Users/mrqwirk/`.

I noticed that after uploading….
They still work, at least on macOS they do. But relative links would probably be better. I’ll look into how o can make them relative and platform friendly

**Comment by sweetppro** [comment]
now they really are fixed
:)

**Comment by shpakovski** [comment]
Thanks!

**Comment by sweetppro** [comment]
oh,
you may want to update the section on installation by SPM in the ReadMe,
Its currently pointing to my repo

**Comment by shpakovski** [comment]
@sweetppro Thanks for the heads up. I cannot commit changes to this project at the moment. Could you please make another PR? 🙏

**Comment by sweetppro** [comment]
No problem,
I’ll do it this afternoon

**Pull request merged**
