### PR TITLE
Major library refactoring

### PR DESCRIPTION
**Pull request by zoul**
See the commit logs for a changelog and rationale. I hope that the changes improve code readability and maintainability and can be merged. It would be a shame for `MASShortcut` to evolve into the hairy ball that became of Shortcut Recorder.

To be done:

- [x] Introduce a separate dispatcher class to bind shortcuts to actions?
- [x] Introduce a separate class to persist bindings to user defaults?
- [x] Add a convenience API to register default shortcuts.
- [x] Write code to enable backward compatibility with Shortcut Recorder?
- [x] Add a simple wrapper API atop the new classes to simplify usage?
- [x] Update documentation
- [x] Normalize whitespace

If there are any code style issues, I propose to resolve them later, after merging, preferably using an automated tool.

### CODE REVIEW

**Comment by zoul** [comment]
Is there any chance of this getting merged, possibly making a 2.0 release as discussed above? The proposed changes no longer apply, but right now I could put some more work to update them for your current master. If we don’t merge the code now, the codebases will soon diverge for good. I think that would be a pity, for both sides.

**Comment by shpakovski** [comment]
Hey Tomáš, 2.0 sounds like the best option for me, but I still have no time for this. Mostly because I do not work on any Mac project at the moment to play with `MASShortcut` in production. However, I really like your code and all improvements.

Is there any way to invite you as a collaborator to my repository so that you can make changes without my approve?

**Comment by shpakovski** [comment]
Got it, done. This is my first collaboration experience on GitHub, so good luck to us. I'm not sure how to start the second version for CocoaPods with your proposed changes. Any advise? Thanks in advance!

**Comment by zoul** [comment]
Great, thank you! I’ll try and prepare a 2.0 branch based both on this pull request and your current master and will ping you when it’s ready.

**Comment by zoul** [comment]
I have rebased the changes on your current master, see #53.

**Pull request closed without merging**
