### PR TITLE
fix cocoa pods support and update ReadMe

### PR DESCRIPTION
**Pull request by sweetppro**

### CODE REVIEW

**Comment by shpakovski** [comment]
Hey @sweetppro 👋 Could you please double-check? Maybe rebase?

**Comment by sweetppro** [comment]
hmm, I've never done a rebase...
how do I do this without messing up?

**Comment by sweetppro** [comment]
> Hey @sweetppro 👋 Could you please double-check? Maybe rebase?

apologies for the loooong delay,
I've just fixed the commit

**Comment by sweetppro** [comment]
its perhaps better to use PR [#166](https://github.com/shpakovski/MASShortcut/pull/166)

**Pull request closed without merging**
