### PR TITLE
Major refactoring for the 2.0 release

### PR DESCRIPTION
**Pull request by zoul**
This is a major, backwards-incompatible refactoring intended to simplify long-term maintenance. See pull request #42 for previous discussion – these are the same changes, only updated for the current master branch.

Vadim, we can review the changes once more and if everything looks fine, we’ll merge this into master? Before that, we can create a 1.x branch to keep the older codebase for people who don’t want to update to 2.0 for whatever reasons.

### CODE REVIEW

**Comment by zoul** [comment]
Sorry, I forgot to address your concern about CocoaPods:

> I'm not sure how to start the second version for CocoaPods with your proposed changes. Any advise?

I’m no CocoaPods expert (I have just started using it), but I think we can continue releasing both 2.x (regular development) and 1.x (bugfixes on the old codebase). According to the [CocoaPods Podfile Guide](http://guides.cocoapods.org/using/the-podfile.html), you can use the `~>` operator to smart-match release version numbers: for example `~>` should stick to the 1.x branch for people who want to.

**Comment by shpakovski** [comment]
Okay Tomáš, I reviewed all changes and `shouldBypass`is the only functionality I would like to restore. Could you please return those lines?

**Comment by zoul** [comment]
Great, thanks! I’m on the `shouldBypass` feature at the moment. You’re right, the recording should be cancelled by Cmd-W and Cmd-Q, but isn’t at the moment. I’ll document the possible cases and fix the Cmd-W/Q input.

**Comment by zoul** [comment]
Done. I have also created a `maintenance-1.x` branch to keep track of the development in the 1.x line. Now you can merge this into master, I’ll test the result in CocoaPods and if everything works, we can release the new version on CocoaPods. You can [add me as a contributor](http://guides.cocoapods.org/making/getting-setup-with-trunk.html) if you want to, so that I can release updates to CocoaPods.

**Comment by shpakovski** [comment]
I already added you as a collaborator, so feel free to merge the Pull Request yourself.

P. S. Please check your Inbox for CocoaPods email verification.

**Comment by shpakovski** [comment]
Please check the Demo launched for the first time with empty user defaults. In this case, Xcode 6.1 generates warnings, the app omits error `-[__NSDictionaryM removeObjectForKey:]: key cannot be nil` into Console and `Command-2` does not work. Thanks in advance!

**Comment by zoul** [comment]
The `removeObjectForKey` was a nice catch, fixed by an explicit nil-check. I have simplified the demo to the basic use case, now it works out of the box.

**Pull request merged**
